development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://usnoyvafugzjku:40e552f98f91e98b8341ad67b84f0287b173b11562f4a7865444e2a6fd0dbc43@ec2-54-243-235-153.compute-1.amazonaws.com:5432/ddmnaj2t7da93j
  channel_prefix: lotusart_production
